project_id = "uvsmkvynhiqpjjotxthi"

[functions.download-tiktok]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false

[functions.generate-variant-image]
verify_jwt = false

[functions.animate-kling]
verify_jwt = false

[functions.poll-kling]
verify_jwt = false

[functions.generate-video-sora]
verify_jwt = false

[functions.get-video-task]
verify_jwt = false
