import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface ValidationResult {
  silhouette_score: number;
  color_score: number;
  branding_score: number;
  packaging_score: number;
  proportion_score: number;
  overall_product_match: number;
  pass: boolean;
  failure_reasons: string[];
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { product_reference_url, generated_image_url, threshold } = await req.json();

    if (!product_reference_url || !generated_image_url) {
      throw new Error("product_reference_url and generated_image_url are required");
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const matchThreshold = threshold ?? 0.85;

    const prompt = `You are a strict product consistency validator for UGC ad generation.

You will receive TWO images:
1. REFERENCE IMAGE: The ground truth product photo uploaded by the user.
2. GENERATED IMAGE: A scene generated by AI that should contain the same product.

Your job is to compare the product visible in the generated image against the reference and score consistency on these dimensions (0.0 to 1.0, where 1.0 = perfect match):

1. silhouette_score — Does the product shape/outline match?
2. color_score — Do the dominant product colors match?
3. branding_score — Are labels, logos, and text on the product consistent?
4. packaging_score — Does the packaging geometry (bottle, box, tube, jar, etc.) match?
5. proportion_score — Are the proportions (height/width ratio, size relative to hands/scene) consistent?

Then compute overall_product_match as the weighted average:
  silhouette: 25%, color: 20%, branding: 25%, packaging: 20%, proportion: 10%

If overall_product_match < ${matchThreshold}, set pass = false.
If silhouette_score < 0.7 OR branding_score < 0.7, set pass = false regardless of overall score.

For failure_reasons, list specific issues in Spanish, e.g.:
- "El color principal del producto no coincide"
- "La silueta es distinta a la referencia"
- "El empaque fue reinterpretado"
- "El branding/etiqueta no coincide"
- "Las proporciones no son consistentes"

If the product is not visible in the generated image at all, all scores should be 0 and pass = false with reason "Producto no visible en la escena generada".

Return ONLY valid JSON, no markdown.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: product_reference_url } },
              { type: "image_url", image_url: { url: generated_image_url } },
            ],
          },
        ],
        tools: [
          {
            type: "function",
            function: {
              name: "report_product_validation",
              description: "Report the product similarity validation results",
              parameters: {
                type: "object",
                properties: {
                  silhouette_score: { type: "number", description: "0-1 shape match" },
                  color_score: { type: "number", description: "0-1 color match" },
                  branding_score: { type: "number", description: "0-1 branding match" },
                  packaging_score: { type: "number", description: "0-1 packaging match" },
                  proportion_score: { type: "number", description: "0-1 proportion match" },
                  overall_product_match: { type: "number", description: "Weighted average" },
                  pass: { type: "boolean", description: "Whether product passes validation" },
                  failure_reasons: {
                    type: "array",
                    items: { type: "string" },
                    description: "List of failure reasons in Spanish",
                  },
                },
                required: [
                  "silhouette_score", "color_score", "branding_score",
                  "packaging_score", "proportion_score", "overall_product_match",
                  "pass", "failure_reasons",
                ],
                additionalProperties: false,
              },
            },
          },
        ],
        tool_choice: { type: "function", function: { name: "report_product_validation" } },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("[validate-product-similarity] AI error:", response.status, errText);

      if (response.status === 429 || response.status === 503) {
        // If rate limited, return a "pass" to not block the pipeline
        return new Response(JSON.stringify({
          silhouette_score: 1, color_score: 1, branding_score: 1,
          packaging_score: 1, proportion_score: 1, overall_product_match: 1,
          pass: true, failure_reasons: [], skipped: true, skip_reason: "Validator unavailable",
        }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }
      throw new Error(`Validation failed: ${response.status}`);
    }

    const result = await response.json();
    const toolCall = result.choices?.[0]?.message?.tool_calls?.[0];

    if (!toolCall?.function?.arguments) {
      // Fallback: try to parse from content
      const content = result.choices?.[0]?.message?.content || "";
      try {
        const parsed = JSON.parse(content.replace(/```json?\n?/g, "").replace(/```/g, "").trim());
        console.log("[validate-product-similarity] Parsed from content:", parsed);
        return new Response(JSON.stringify(parsed), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      } catch {
        console.error("[validate-product-similarity] Could not parse response");
        // Return pass to not block
        return new Response(JSON.stringify({
          silhouette_score: 1, color_score: 1, branding_score: 1,
          packaging_score: 1, proportion_score: 1, overall_product_match: 1,
          pass: true, failure_reasons: [], skipped: true, skip_reason: "Could not parse validation",
        }), { headers: { ...corsHeaders, "Content-Type": "application/json" } });
      }
    }

    let validation: ValidationResult;
    if (typeof toolCall.function.arguments === "string") {
      validation = JSON.parse(toolCall.function.arguments);
    } else {
      validation = toolCall.function.arguments;
    }

    console.log("[validate-product-similarity] Result:", JSON.stringify(validation));

    return new Response(JSON.stringify(validation), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e: any) {
    console.error("[validate-product-similarity] error:", e);
    return new Response(JSON.stringify({ error: e?.message || "Validation error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
